mysql:
  host:
  user:
  pass:
  port:
  db:
max: 5
dontPlace:
  - SAND
  - GRAVEL
  - ANVIL
  - GRASS_BLOCK
  - WHITE_CONCRETE_POWDER
  - ORANGE_CONCRETE_POWDER
  - MAGENTA_CONCRETE_POWDER
  - LIGHT_BLUE_CONCRETE_POWDER
  - YELLOW_CONCRETE_POWDER
  - LIME_CONCRETE_POWDER
  - PINK_CONCRETE_POWDER
  - GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_CONCRETE_POWDER
  - CYAN_CONCRETE_POWDER
  - PURPLE_CONCRETE_POWDER
  - BLUE_CONCRETE_POWDER
  - BROWN_CONCRETE_POWDER
  - GREEN_CONCRETE_POWDER
  - RED_CONCRETE_POWDER
  - BLACK_CONCRETE_POWDER